//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Animals
    {
        public int Id { get; set; }
        public int TypeColorId { get; set; }
        public int LocationId { get; set; }
        public string Name { get; set; }

        [ForeignKey("TypeColorId")]
        public virtual AnimalTypeColors AnimalTypeColors { get; set; }

        [ForeignKey("LocationId")]
        public virtual Locations Locations { get; set; }
    }
}
