//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AnimalTypeColors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimalTypeColors()
        {
            this.Animals = new HashSet<Animals>();
        }
    
        public int Id { get; set; }
        public int ColorId { get; set; }
        public int TypeId { get; set; }
        public string TypeColorName { get; set; }

        [ForeignKey("ColorId")]
        public virtual AnimalColors AnimalColors { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animals> Animals { get; set; }

        [ForeignKey("TypeId")]
        public virtual AnimalTypes AnimalTypes { get; set; }
    }
}
